### PR TITLE
Add mappings to navigate between splits using ctrl+j/k/h/l

### PR DESCRIPTION
**Pull request by barboza**

### CODE REVIEW

**Comment by josemarluedke** [comment]
You can also use ctrl + w + (h/j/k/l).

**Comment by josemarluedke** [comment]
@barboza unfortunately the `<C-H>` is not working. Could you check what is going on?

**Comment by barboza** [comment]
I know about the ctrl + w + h, thats the base bindings im remapping, these ones are easier and you can use it together with https://github.com/christoomey/vim-tmux-navigator.

About the `<C-H>` not working: there is already a mapping for it (vimrc line 379), is it required to be `<C-H>`?

**Comment by josemarluedke** [comment]
I did try to get rid of that to see if `<C-H` worked fine for the split, but no luck.

**Comment by barboza** [comment]
Just tested again, it works on vim but not on neovim.

**Pull request merged**
